### ISSUE TITLE
Cant install package :(

### ISSUE THREAD

**Issue by p10tyr** [damon-e-drake/tokenstring#1]
Install failed. Rolling back...
Install-Package : Could not install package 'TokenString 0.9.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible 
with that framework. For more information, contact the package author.
At line:1 char:1
- Install-Package TokenString
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by damon-e-drake** [comment]
Problem is it is compiled only for Net 4.5 will fix this issue and post the correct nuget installer.
