### ISSUE TITLE
ShortGuid

### ISSUE THREAD

**Issue by virzak** [damon-e-drake/tokenstring#2]
Hello,

Is there a repo for [ShortGuid](https://www.nuget.org/packages/ShortGuid)?

Currently using it in a .NET Framework application and looking into converting it to .NET Core.

I wanted to send a PR targeting Short Guid to .NET standard, but I don't know where it is.

**Comment by damon-e-drake** [comment]
There is not a repo on here for [ShortGuid](https://www.nuget.org/packages/ShortGuid). I was just going through all these public repos and determining which ones to keep and that is one I am missing as well. I am going to look through some old code backups and see if I can resurrect it on here. I was just about to do the same and update it to .Net Core for a project I am messing around with.

I am going to leave this open until I get the repo up and going and then I will close it and send you a link.

Thanks

**Comment by damon-e-drake** [comment]
I posted the project here: [ShortGuid](https://github.com/damon-e-drake/short-guid) 

I also  updated the Nuget package as well.
